# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: stagingpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  cottonwood.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "72;_{dbv{mh1z;#R{GB)n+LdWJ9Y!+f]#<W_%WHwC5[`zh#v-dJ{]:kZUl<DV}we"
      secure_auth_key: "]A7@T;[Aa_W+ai/n$bpa6^xlis?PnDI(hbDEG#&=lftq?)3xTc!bX2;PGLr%]%{R"
      logged_in_key: "jC.-PIIz5ia%Tjh2JR-`yw8%E731IwF51<T@:eFFQ-:O;+)ONBGS:&_eIl^Kd6k;"
      nonce_key: "I5bW6_gWE:MlbC*O|5/}v_:tg%*>z&UbX)>r;_`Yc4M+FW.#HSZ!@kCPw:rd?S-6"
      auth_salt: "VWqU4C(Si$fbI<s4zjw<6V6ygce(?{x}AhDZ9frxx)-kZw$[kz[r5,kxPvSFMTd;"
      secure_auth_salt: "HMo{}n|JRH=)9S8(z}-EPfmpf4&RSly,>^{53w5|w@KriZXGwDN^[O*.O%Q;;RW`"
      logged_in_salt: "KG5=71M-)bggu}{zJC?[,QAVbWhU#{ZC&KTq)WUlW`Gj#YJ.as<h4^*0`C]_`W#%"
      nonce_salt: "(#Vn&f3%kHBYRwv0?s0{Ytk#_YArUD$7#20Zbi[k.rU={->ciER;#@*xZ}Edo+`:"
