<?php
/** no direct access **/
defined('_WPLEXEC') or die('Restricted access');

_wpl_import('libraries.pdfflyer.mpdf');

/**
 * PDF Library
 * @author Howard <howard@realtyna.com>
 * @since WPL1.0.0
 * @date 01/17/2014
 * @package WPL PRO
 */
class wpl_pdf
{
	var $creator = 'WPL';
	var $author = 'WPL (WordPress Property listing)';
	var $page_title = 'PDF Flyer'; # page title
	var $pdf_page_orientation = 'portrait'; # Page orientation (P=portrait, L=landscape)
	var $pdf_unit = 'mm'; # Document unit of measure [pt=point, mm=millimeter, cm=centimeter, in=inch]
	var $pdf_page_format = 'A4'; # Page format
	var $pdf_subject = 'Property flyer';
	var $pdf_header_logo = '';
	var $pdf_header_logo_width = 0;
	var $pdf_header_title = 'Property flyer';
	var $pdf_header_description = 'Generated by WPL (wpl.realtyna.com)';
	var $pdf_font_name_main = 'helvetica'; # Default main font name
	var $pdf_font_name_data = 'helvetica'; # Default data font name
	var $pdf_font_size_main = 10; # Default main font size
	var $pdf_font_size_data = 8; # Default data font size
	var $pdf_font_monospaced = 'courier'; # Default monospaced font name
	var $pdf_margin_left = 15;
	var $pdf_margin_right = 15;
	var $pdf_margin_top = 27;
	var $pdf_margin_bottom = 25;
	var $pdf_margin_header = 5;
	var $pdf_margin_footer = 10;
	var $pdf_image_scale_ratio = 1.25; # Ratio used to adjust the conversion of pixels to user units
	var $pdf_font_name = 'helvetica'; # Default font name
	var $pdf_font_size = 14; # Default font size
    var $pdf_language = 'en';
	var $print_header = false;
	var $print_footer = false;
	
    /**
     * Returns DOMPDF instance
     * @author Howard <howard@realtyna.com>
     * @return \mPDF
     */
	public function get_PDF_object()
	{
        $pdf = new mPDF('', $this->pdf_page_format, 0, '', 0, 0, 0, 0, 0, 0);
        
        $pdf->showImageErrors = false;
        $pdf->debug = false;
        
        $pdf->SetTitle($this->pdf_subject);
        $pdf->SetSubject($this->pdf_subject);
        $pdf->SetAuthor($this->author);
        $pdf->SetCreator($this->creator);
        
        /** apply filters **/
		_wpl_import('libraries.filters');
		@extract(wpl_filters::apply('wpl_pdf_instance', array('pdf'=>$pdf, 'wpl_pdf'=>$this)));
        
		return $pdf;
	}
    
    /**
     * Removes http protocol and domain name from url and return the rest
     * @author Howard <howard@realtyna.com>
     * @static
     * @param string $mainurl
     * @return string
     */
    public static function get_fixed_url($mainurl = '')
    {
        /** first validation **/
        if(trim($mainurl) == '') return '';
        
        $domain = wpl_global::domain($mainurl);
        if(strpos($domain, '127.0.0.1') !== false or strpos($domain, 'localhost') !== false) return $mainurl;
        
        $url = str_replace('https://', '', $mainurl);
        $url = str_replace('http://', '', $url);
        $url = str_replace('www.', '', $url);
        $url = str_replace($domain, '', $url);
        
        $path = $url;
        $wpcontent_pos = strpos($url, '/wp-content/');
        if($wpcontent_pos) $path = substr($url, $wpcontent_pos);
        
        $url = rtrim($url, '/ ');
        $path = trim($path, '/ ');
        
        if(@!wpl_file::read(wpl_global::get_wp_root_path().$path)) return $mainurl;
        else return $url;
    }
}